[toolchain]
anchor_version = "1.0.2"
solana_version = "3.1.8"

[features]
resolution = true
skip-lint = false

[programs.localnet]
secp256k1_anchor_program = "G7SyMsDAgVFFzQoLx6VsG8vaufuYvxmyfvFeHQbKXe1T"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm mocha --import=tsx -t 1000000 tests/litesvm.test.ts"

[hooks]
